# Generated by Django 5.1.3 on 2024-11-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_GestionUsuariosPerfil', '0003_datosacademicos_experiencialaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
