# Generated by Django 5.1.3 on 2024-11-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_GestionUsuariosPerfil', '0004_alter_perfilusuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
