# Generated by Django 5.1.2 on 2024-11-20 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_GestionUsuariosPerfil', '0005_alter_experiencialaboral_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_GestionUsuariosPerfil.perfilusuario'),
        ),
    ]
