# Generated by Django 5.1.2 on 2024-11-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_GestionUsuariosPerfil', '0008_remove_experiencialaboral_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosacademicos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='perfil',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='academicos', to='API_GestionUsuariosPerfil.perfilusuario'),
            preserve_default=False,
        ),
    ]
