# Generated by Django 5.1.2 on 2024-11-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_GestionUsuariosPerfil', '0009_remove_datosacademicos_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacademicos',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academicos', to='API_GestionUsuariosPerfil.perfilusuario'),
        ),
    ]
